Vagrant.configure("2") do |config|
  config.vm.box = "sbeliakou/centos"
  config.vm.define "master" do |master|
    master.vm.hostname = "master-node"
    master.vm.network :private_network, ip: "192.168.56.15" 
    master.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
      vb.name = "master-node"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
      vb.memory = "2048"
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker-node"
    worker.vm.network :private_network, ip: "192.168.56.16" 
    worker.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
      vb.name = "worker-node"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
      vb.memory = "2048"
    end
  end
end
